// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/SC)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        others - reserved
// 0x10 : Data signal of challenge1axi_V
//        bit 3~0 - challenge1axi_V[3:0] (Read/Write)
//        others  - reserved
// 0x14 : reserved
// 0x18 : Data signal of challenge2axi_V
//        bit 3~0 - challenge2axi_V[3:0] (Read/Write)
//        others  - reserved
// 0x1c : reserved
// 0x20 : Data signal of responseaxi_V
//        bit 7~0 - responseaxi_V[7:0] (Read)
//        others  - reserved
// 0x24 : Control signal of responseaxi_V
//        bit 0  - responseaxi_V_ap_vld (Read/COR)
//        others - reserved
// 0x28 : Data signal of tuneraxi_top_1_V
//        bit 31~0 - tuneraxi_top_1_V[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of tuneraxi_top_2_V
//        bit 31~0 - tuneraxi_top_2_V[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of tuneraxi_top_3_V
//        bit 31~0 - tuneraxi_top_3_V[31:0] (Read/Write)
// 0x3c : reserved
// 0x40 : Data signal of tuneraxi_top_4_V
//        bit 31~0 - tuneraxi_top_4_V[31:0] (Read/Write)
// 0x44 : reserved
// 0x48 : Data signal of tuneraxi_btm_1_V
//        bit 31~0 - tuneraxi_btm_1_V[31:0] (Read/Write)
// 0x4c : reserved
// 0x50 : Data signal of tuneraxi_btm_2_V
//        bit 31~0 - tuneraxi_btm_2_V[31:0] (Read/Write)
// 0x54 : reserved
// 0x58 : Data signal of tuneraxi_btm_3_V
//        bit 31~0 - tuneraxi_btm_3_V[31:0] (Read/Write)
// 0x5c : reserved
// 0x60 : Data signal of tuneraxi_btm_4_V
//        bit 31~0 - tuneraxi_btm_4_V[31:0] (Read/Write)
// 0x64 : reserved
// 0x68 : Data signal of output1axi_V
//        bit 7~0 - output1axi_V[7:0] (Read)
//        others  - reserved
// 0x6c : Control signal of output1axi_V
//        bit 0  - output1axi_V_ap_vld (Read/COR)
//        others - reserved
// 0x70 : Data signal of output2axi_V
//        bit 7~0 - output2axi_V[7:0] (Read)
//        others  - reserved
// 0x74 : Control signal of output2axi_V
//        bit 0  - output2axi_V_ap_vld (Read/COR)
//        others - reserved
// 0x78 : Data signal of startaxi_V
//        bit 0  - startaxi_V[0] (Read/Write)
//        others - reserved
// 0x7c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_AP_CTRL               0x00
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_GIE                   0x04
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_IER                   0x08
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_ISR                   0x0c
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_CHALLENGE1AXI_V_DATA  0x10
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_CHALLENGE1AXI_V_DATA  4
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_CHALLENGE2AXI_V_DATA  0x18
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_CHALLENGE2AXI_V_DATA  4
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_RESPONSEAXI_V_DATA    0x20
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_RESPONSEAXI_V_DATA    8
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_RESPONSEAXI_V_CTRL    0x24
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_TUNERAXI_TOP_1_V_DATA 0x28
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_TUNERAXI_TOP_1_V_DATA 32
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_TUNERAXI_TOP_2_V_DATA 0x30
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_TUNERAXI_TOP_2_V_DATA 32
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_TUNERAXI_TOP_3_V_DATA 0x38
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_TUNERAXI_TOP_3_V_DATA 32
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_TUNERAXI_TOP_4_V_DATA 0x40
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_TUNERAXI_TOP_4_V_DATA 32
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_TUNERAXI_BTM_1_V_DATA 0x48
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_TUNERAXI_BTM_1_V_DATA 32
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_TUNERAXI_BTM_2_V_DATA 0x50
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_TUNERAXI_BTM_2_V_DATA 32
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_TUNERAXI_BTM_3_V_DATA 0x58
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_TUNERAXI_BTM_3_V_DATA 32
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_TUNERAXI_BTM_4_V_DATA 0x60
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_TUNERAXI_BTM_4_V_DATA 32
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_OUTPUT1AXI_V_DATA     0x68
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_OUTPUT1AXI_V_DATA     8
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_OUTPUT1AXI_V_CTRL     0x6c
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_OUTPUT2AXI_V_DATA     0x70
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_OUTPUT2AXI_V_DATA     8
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_OUTPUT2AXI_V_CTRL     0x74
#define XLONG_PUF_AXI_INTERFACE_AXILITES_ADDR_STARTAXI_V_DATA       0x78
#define XLONG_PUF_AXI_INTERFACE_AXILITES_BITS_STARTAXI_V_DATA       1

