// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xlong_puf_axi_interface.h"

extern XLong_puf_axi_interface_Config XLong_puf_axi_interface_ConfigTable[];

XLong_puf_axi_interface_Config *XLong_puf_axi_interface_LookupConfig(u16 DeviceId) {
	XLong_puf_axi_interface_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XLONG_PUF_AXI_INTERFACE_NUM_INSTANCES; Index++) {
		if (XLong_puf_axi_interface_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XLong_puf_axi_interface_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XLong_puf_axi_interface_Initialize(XLong_puf_axi_interface *InstancePtr, u16 DeviceId) {
	XLong_puf_axi_interface_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XLong_puf_axi_interface_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XLong_puf_axi_interface_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

