# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ucsd-ece268-puf/constraints.xdc

# Block Designs: bd/long_puf/long_puf.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==long_puf || ORIG_REF_NAME==long_puf} -quiet] -quiet

# IP: bd/long_puf/ip/long_puf_long_puf_axi_interface_0_1/long_puf_long_puf_axi_interface_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==long_puf_long_puf_axi_interface_0_1 || ORIG_REF_NAME==long_puf_long_puf_axi_interface_0_1} -quiet] -quiet

# IP: bd/long_puf/ip/long_puf_processing_system7_0_0/long_puf_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==long_puf_processing_system7_0_0 || ORIG_REF_NAME==long_puf_processing_system7_0_0} -quiet] -quiet

# IP: bd/long_puf/ip/long_puf_ps7_0_axi_periph_0/long_puf_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==long_puf_ps7_0_axi_periph_0 || ORIG_REF_NAME==long_puf_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/long_puf/ip/long_puf_rst_ps7_0_50M_0/long_puf_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==long_puf_rst_ps7_0_50M_0 || ORIG_REF_NAME==long_puf_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/long_puf/ip/long_puf_long_puf_0_0/long_puf_long_puf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==long_puf_long_puf_0_0 || ORIG_REF_NAME==long_puf_long_puf_0_0} -quiet] -quiet

# IP: bd/long_puf/ip/long_puf_auto_pc_0/long_puf_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==long_puf_auto_pc_0 || ORIG_REF_NAME==long_puf_auto_pc_0} -quiet] -quiet

# XDC: bd/long_puf/long_puf_ooc.xdc
