# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.cache/wt [current_project]
set_property parent.project_path C:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/users/mayunk/desktop/ece268/long_puf/long_puf.srcs/sources_1/imports/ucsd-ece268-puf
  c:/Users/Mayunk/Desktop/CSE237C/final_project/mdk/orca_swirq/riscvonpynq/orca/lmb
  c:/Users/Mayunk/long_puf_axi/solution1/impl/ip
} [current_project]
set_property ip_output_repo c:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/hdl/long_puf_wrapper.vhd
add_files C:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/long_puf.bd
set_property used_in_implementation false [get_files -all c:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/ip/long_puf_long_puf_axi_interface_0_1/constraints/long_puf_axi_interface_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/ip/long_puf_processing_system7_0_0/long_puf_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/ip/long_puf_rst_ps7_0_50M_0/long_puf_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/ip/long_puf_rst_ps7_0_50M_0/long_puf_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/ip/long_puf_rst_ps7_0_50M_0/long_puf_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/ip/long_puf_auto_pc_0/long_puf_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/long_puf_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/constrs_1/imports/ucsd-ece268-puf/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/constrs_1/imports/ucsd-ece268-puf/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top long_puf_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef long_puf_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file long_puf_wrapper_utilization_synth.rpt -pb long_puf_wrapper_utilization_synth.pb"
