// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XPUF_AXI_INTERFACE_V2_H
#define XPUF_AXI_INTERFACE_V2_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xpuf_axi_interface_v2_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XPuf_axi_interface_v2_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XPuf_axi_interface_v2;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XPuf_axi_interface_v2_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XPuf_axi_interface_v2_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XPuf_axi_interface_v2_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XPuf_axi_interface_v2_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XPuf_axi_interface_v2_Initialize(XPuf_axi_interface_v2 *InstancePtr, u16 DeviceId);
XPuf_axi_interface_v2_Config* XPuf_axi_interface_v2_LookupConfig(u16 DeviceId);
int XPuf_axi_interface_v2_CfgInitialize(XPuf_axi_interface_v2 *InstancePtr, XPuf_axi_interface_v2_Config *ConfigPtr);
#else
int XPuf_axi_interface_v2_Initialize(XPuf_axi_interface_v2 *InstancePtr, const char* InstanceName);
int XPuf_axi_interface_v2_Release(XPuf_axi_interface_v2 *InstancePtr);
#endif

void XPuf_axi_interface_v2_Start(XPuf_axi_interface_v2 *InstancePtr);
u32 XPuf_axi_interface_v2_IsDone(XPuf_axi_interface_v2 *InstancePtr);
u32 XPuf_axi_interface_v2_IsIdle(XPuf_axi_interface_v2 *InstancePtr);
u32 XPuf_axi_interface_v2_IsReady(XPuf_axi_interface_v2 *InstancePtr);
void XPuf_axi_interface_v2_EnableAutoRestart(XPuf_axi_interface_v2 *InstancePtr);
void XPuf_axi_interface_v2_DisableAutoRestart(XPuf_axi_interface_v2 *InstancePtr);

void XPuf_axi_interface_v2_Set_challenge1axi_V(XPuf_axi_interface_v2 *InstancePtr, u32 Data);
u32 XPuf_axi_interface_v2_Get_challenge1axi_V(XPuf_axi_interface_v2 *InstancePtr);
void XPuf_axi_interface_v2_Set_challenge2axi_V(XPuf_axi_interface_v2 *InstancePtr, u32 Data);
u32 XPuf_axi_interface_v2_Get_challenge2axi_V(XPuf_axi_interface_v2 *InstancePtr);
u32 XPuf_axi_interface_v2_Get_responseaxi_V(XPuf_axi_interface_v2 *InstancePtr);
u32 XPuf_axi_interface_v2_Get_responseaxi_V_vld(XPuf_axi_interface_v2 *InstancePtr);
void XPuf_axi_interface_v2_Set_tuneraxi_V(XPuf_axi_interface_v2 *InstancePtr, u32 Data);
u32 XPuf_axi_interface_v2_Get_tuneraxi_V(XPuf_axi_interface_v2 *InstancePtr);
u32 XPuf_axi_interface_v2_Get_output1axi_V(XPuf_axi_interface_v2 *InstancePtr);
u32 XPuf_axi_interface_v2_Get_output1axi_V_vld(XPuf_axi_interface_v2 *InstancePtr);
u32 XPuf_axi_interface_v2_Get_output2axi_V(XPuf_axi_interface_v2 *InstancePtr);
u32 XPuf_axi_interface_v2_Get_output2axi_V_vld(XPuf_axi_interface_v2 *InstancePtr);
void XPuf_axi_interface_v2_Set_startaxi_V(XPuf_axi_interface_v2 *InstancePtr, u32 Data);
u32 XPuf_axi_interface_v2_Get_startaxi_V(XPuf_axi_interface_v2 *InstancePtr);

void XPuf_axi_interface_v2_InterruptGlobalEnable(XPuf_axi_interface_v2 *InstancePtr);
void XPuf_axi_interface_v2_InterruptGlobalDisable(XPuf_axi_interface_v2 *InstancePtr);
void XPuf_axi_interface_v2_InterruptEnable(XPuf_axi_interface_v2 *InstancePtr, u32 Mask);
void XPuf_axi_interface_v2_InterruptDisable(XPuf_axi_interface_v2 *InstancePtr, u32 Mask);
void XPuf_axi_interface_v2_InterruptClear(XPuf_axi_interface_v2 *InstancePtr, u32 Mask);
u32 XPuf_axi_interface_v2_InterruptGetEnabled(XPuf_axi_interface_v2 *InstancePtr);
u32 XPuf_axi_interface_v2_InterruptGetStatus(XPuf_axi_interface_v2 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
