// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpuf_axi_interface.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPuf_axi_interface_CfgInitialize(XPuf_axi_interface *InstancePtr, XPuf_axi_interface_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPuf_axi_interface_Start(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_AP_CTRL) & 0x80;
    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XPuf_axi_interface_IsDone(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XPuf_axi_interface_IsIdle(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XPuf_axi_interface_IsReady(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XPuf_axi_interface_EnableAutoRestart(XPuf_axi_interface *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XPuf_axi_interface_DisableAutoRestart(XPuf_axi_interface *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_AP_CTRL, 0);
}

void XPuf_axi_interface_Set_challenge1axi_V(XPuf_axi_interface *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_CHALLENGE1AXI_V_DATA, Data);
}

u32 XPuf_axi_interface_Get_challenge1axi_V(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_CHALLENGE1AXI_V_DATA);
    return Data;
}

void XPuf_axi_interface_Set_challenge2axi_V(XPuf_axi_interface *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_CHALLENGE2AXI_V_DATA, Data);
}

u32 XPuf_axi_interface_Get_challenge2axi_V(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_CHALLENGE2AXI_V_DATA);
    return Data;
}

u32 XPuf_axi_interface_Get_responseaxi_V(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_RESPONSEAXI_V_DATA);
    return Data;
}

u32 XPuf_axi_interface_Get_responseaxi_V_vld(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_RESPONSEAXI_V_CTRL);
    return Data & 0x1;
}

void XPuf_axi_interface_Set_tuneraxi_V(XPuf_axi_interface *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_TUNERAXI_V_DATA, (u32)(Data));
    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_TUNERAXI_V_DATA + 4, (u32)(Data >> 32));
}

u64 XPuf_axi_interface_Get_tuneraxi_V(XPuf_axi_interface *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_TUNERAXI_V_DATA);
    Data += (u64)XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_TUNERAXI_V_DATA + 4) << 32;
    return Data;
}

u32 XPuf_axi_interface_Get_output1axi_V(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_OUTPUT1AXI_V_DATA);
    return Data;
}

u32 XPuf_axi_interface_Get_output1axi_V_vld(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_OUTPUT1AXI_V_CTRL);
    return Data & 0x1;
}

u32 XPuf_axi_interface_Get_output2axi_V(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_OUTPUT2AXI_V_DATA);
    return Data;
}

u32 XPuf_axi_interface_Get_output2axi_V_vld(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_OUTPUT2AXI_V_CTRL);
    return Data & 0x1;
}

void XPuf_axi_interface_Set_startaxi_V(XPuf_axi_interface *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_STARTAXI_V_DATA, Data);
}

u32 XPuf_axi_interface_Get_startaxi_V(XPuf_axi_interface *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_STARTAXI_V_DATA);
    return Data;
}

void XPuf_axi_interface_InterruptGlobalEnable(XPuf_axi_interface *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_GIE, 1);
}

void XPuf_axi_interface_InterruptGlobalDisable(XPuf_axi_interface *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_GIE, 0);
}

void XPuf_axi_interface_InterruptEnable(XPuf_axi_interface *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_IER);
    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_IER, Register | Mask);
}

void XPuf_axi_interface_InterruptDisable(XPuf_axi_interface *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_IER);
    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_IER, Register & (~Mask));
}

void XPuf_axi_interface_InterruptClear(XPuf_axi_interface *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPuf_axi_interface_WriteReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_ISR, Mask);
}

u32 XPuf_axi_interface_InterruptGetEnabled(XPuf_axi_interface *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_IER);
}

u32 XPuf_axi_interface_InterruptGetStatus(XPuf_axi_interface *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPuf_axi_interface_ReadReg(InstancePtr->Axilites_BaseAddress, XPUF_AXI_INTERFACE_AXILITES_ADDR_ISR);
}

