# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/ip/long_puf_long_puf_axi_interface_0_1/long_puf_long_puf_axi_interface_0_1.xci
# IP: The module: 'long_puf_long_puf_axi_interface_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/ip/long_puf_long_puf_axi_interface_0_1/constraints/long_puf_axi_interface_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'long_puf_long_puf_axi_interface_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/ip/long_puf_long_puf_axi_interface_0_1/long_puf_long_puf_axi_interface_0_1.xci
# IP: The module: 'long_puf_long_puf_axi_interface_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mayunk/Desktop/ECE268/long_puf/long_puf.srcs/sources_1/bd/long_puf/ip/long_puf_long_puf_axi_interface_0_1/constraints/long_puf_axi_interface_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'long_puf_long_puf_axi_interface_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
